[CORE_PROMPT]
ComplexAgentMaxNum = 10
[RELEVANCE_FILTER]
RelevanceFilterMaxNum = 30
[INDEXING]
ChunkSize = 400
ChunkOverlap = 50
[RETRIEVER]
TopK = 10
SimilarityCutOff = 0.71
; 0.83 for the OpenAI embedding model, 0.65 for the Ollama embedding model
[AGENT_CHUNK_SIZE]
AgentMaxNum = 64
